export const UPDATE_USER_INPUT_VALIDATION = 'UPDATE_USER_INPUT_VALIDATION';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const SAVE_USERS_TO_STORE = 'SAVE_USERS_TO_STORE';
export const SAVE_SINGLE_USER_TO_STORE = 'SAVE_SINGLE_USER_TO_STORE';
export const ENABLE_SUBMIT = 'ENABLE_SUBMIT';
export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const DELETE_USER = 'DELETE_USER';
export const SIGNAL_CREATING = 'SIGNAL_CREATING';
export const SIGNAL_UPDATING = 'SIGNAL_UPDATING';
export const SIGNAL_FETCHING = 'SIGNAL_FETCHING';
export const SIGNAL_DELETING = 'SIGNAL_DELETING';
export const SORT_USERS = 'SORT_USERS';

export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const DISPLAY_CONFIRM_ACTION_DIALOG = 'DISPLAY_CONFIRM_ACTION_DIALOG';
